import fs from "node:fs";
import path from "node:path";

import Ajv2020 from "ajv/dist/2020.js";
import { parse, stringify } from "yaml";

const schema = JSON.parse(fs.readFileSync(new URL("../.github/issue-workflow-config.schema.json", import.meta.url), "utf8"));
const ajv = new Ajv2020({ allErrors: true, strict: true });
const validateSchema = ajv.compile(schema);

export const CONFIG_PATH = ".github/issue-workflow.yml";
export const PLAN_DIRECTORY = ".github/issue-plans";
export const CALLER_WORKFLOW_PATH = ".github/workflows/issue-workflow.yml";
export const SKILL_DIRECTORY = ".codex/skills/iwf-plan";

export function defaultConfig({
  repository = "sine-io/issue-workflow-kit",
  revision,
  cliVersion,
  model = "gpt-5.6-sol",
} = {}) {
  if (!revision) throw new Error("an exact kit revision tag is required");
  if (!cliVersion) throw new Error("an exact Codex CLI version is required");
  return {
    schemaVersion: "iwf-config/v2",
    kit: {
      repository,
      revision,
      reusableWorkflow: ".github/workflows/issue-workflow-v2.yml",
    },
    plans: { directory: PLAN_DIRECTORY },
    runner: {
      provider: "codex",
      cliVersion,
      model,
      promptRevision: "runner-prompt/v1",
      skillRevision: "iwf-plan/v2",
      timeoutSeconds: 7200,
    },
    orchestration: {
      serial: true,
      transientRetries: 1,
      reviews: ["spec", "code"],
      mergeMethod: "squash",
      requiredChecks: ["test"],
    },
    secrets: {
      githubToken: "IWF_TOKEN",
      codexApiKey: "CODEX_API_KEY",
    },
  };
}

export function configText(config) {
  return `# Generated by iwf init. Pin revisions; update through a reviewed planning change.\n${stringify(config, {
    lineWidth: 0,
    sortMapEntries: false,
  })}`;
}

export function parseConfig(source) {
  let value;
  try {
    value = parse(String(source), { uniqueKeys: true, maxAliasCount: 0, prettyErrors: true });
  } catch (error) {
    throw new Error(`configuration YAML is invalid: ${error.message}`);
  }
  return value;
}

export function validateConfig(config) {
  if (!validateSchema(config)) {
    const details = (validateSchema.errors || []).map((error) => `${error.instancePath || "/"} ${error.message}`);
    throw new Error(`configuration validation failed: ${details.join("; ")}`);
  }
  return config;
}

export function readConfig(file = CONFIG_PATH) {
  const resolved = path.resolve(file);
  return validateConfig(parseConfig(fs.readFileSync(resolved, "utf8")));
}

export function assertPlanMatchesConfig(plan, config) {
  const errors = [];
  if (plan.schemaVersion !== "2.0") return;
  if (plan.workflow.repository !== config.kit.repository) errors.push("plan workflow.repository differs from configuration");
  if (plan.workflow.revision !== config.kit.revision) errors.push("plan workflow.revision differs from configuration");
  if (plan.workflow.reusableWorkflow !== config.kit.reusableWorkflow) errors.push("plan reusable workflow differs from configuration");
  for (const [planKey, configKey] of [
    ["provider", "provider"],
    ["cliVersion", "cliVersion"],
    ["model", "model"],
    ["promptRevision", "promptRevision"],
    ["skillRevision", "skillRevision"],
  ]) {
    if (plan.runner[planKey] !== config.runner[configKey]) errors.push(`plan runner.${planKey} differs from configuration`);
  }
  const configuredChecks = [...config.orchestration.requiredChecks].sort().join("\n");
  for (const task of plan.epics.flatMap((epic) => epic.tasks)) {
    if (task.execution.maxRuntimeSeconds > config.runner.timeoutSeconds) {
      errors.push(`${task.id} runtime exceeds configured Runner timeout`);
    }
    if ([...task.execution.requiredChecks].sort().join("\n") !== configuredChecks) {
      errors.push(`${task.id} required checks differ from configuration`);
    }
  }
  if (errors.length) throw new Error(errors.join("; "));
}

export function assertCallerMatchesConfig(source, config) {
  let workflow;
  try {
    workflow = parse(String(source), { uniqueKeys: true, maxAliasCount: 0, prettyErrors: true });
  } catch (error) {
    throw new Error(`caller workflow YAML is invalid: ${error.message}`);
  }
  const job = workflow?.jobs?.["issue-workflow"];
  const expectedUse = `${config.kit.repository}/${config.kit.reusableWorkflow}@${config.kit.revision}`;
  const errors = [];
  if (job?.uses !== expectedUse) errors.push(`caller workflow must use ${expectedUse}`);
  if (job?.with?.kit_repository !== config.kit.repository) errors.push("caller kit_repository differs from configuration");
  if (job?.with?.kit_revision !== config.kit.revision) errors.push("caller kit_revision differs from configuration");
  if (job?.with?.codex_version !== config.runner.cliVersion) errors.push("caller codex_version differs from configuration");
  if (job?.secrets?.IWF_TOKEN !== "${{ secrets.IWF_TOKEN }}"
    || job?.secrets?.CODEX_API_KEY !== "${{ secrets.CODEX_API_KEY }}") {
    errors.push("caller must map each split secret to its matching reusable-workflow secret");
  }
  if (!String(workflow?.concurrency?.group || "").startsWith("iwf-caller-")) errors.push("caller must use its dedicated concurrency group");
  if (errors.length) throw new Error(errors.join("; "));
  return workflow;
}

function rawCallerWorkflow(config, { defaultBranch = "main" } = {}) {
  const uses = `${config.kit.repository}/${config.kit.reusableWorkflow}@${config.kit.revision}`;
  return `name: Issue Workflow Kit\n\non:\n  workflow_dispatch:\n  push:\n    branches:\n      - ${defaultBranch}\n    paths:\n      - \".github/issue-plans/**\"\n      - \".github/issue-workflow.yml\"\n  schedule:\n    - cron: \"17 * * * *\"\n\npermissions:\n  contents: read\n\nconcurrency:\n  group: iwf-\${{ github.repository }}\n  cancel-in-progress: false\n\njobs:\n  issue-workflow:\n    uses: ${uses}\n    with:\n      config-path: ${CONFIG_PATH}\n    secrets:\n      IWF_TOKEN: \${{ secrets.IWF_TOKEN }}\n      CODEX_API_KEY: \${{ secrets.CODEX_API_KEY }}\n`;
}

export function callerWorkflow(config, options = {}) {
  return rawCallerWorkflow(config, options).replace(
    `      config-path: ${CONFIG_PATH}\n`,
      `      config-path: ${CONFIG_PATH}\n      kit_repository: ${config.kit.repository}\n      kit_revision: ${config.kit.revision}\n      codex_version: ${config.runner.cliVersion}\n`,
  ).replace(
    `      - ".github/issue-workflow.yml"\n`,
    `      - ".github/issue-workflow.yml"\n      - ".github/workflows/issue-workflow.yml"\n`,
  ).replace("group: iwf-${{ github.repository }}", "group: iwf-caller-${{ github.repository }}");
}

function walkJson(directory, files) {
  if (!fs.existsSync(directory)) return;
  for (const entry of fs.readdirSync(directory, { withFileTypes: true }).sort((left, right) => left.name.localeCompare(right.name))) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) walkJson(file, files);
    else if (entry.isFile() && entry.name.endsWith(".json")) files.push(file);
  }
}

export function findPlanFiles(root, config) {
  const directory = path.resolve(root, config.plans.directory);
  const files = [];
  walkJson(directory, files);
  return files;
}
